FROM alpine:3.12 as base
RUN apk update \
    && apk upgrade \
    && apk add nodejs npm openssl
WORKDIR /app

FROM base as run
CMD npm i \
    && openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
        -subj "/C=AU/O=app" \
        -keyout ssl.key -out ssl.cert \
    && npm start 